#!/bin/bash
# Quick Start Guide: Control Isaac Sim Robot with Prompts

echo "════════════════════════════════════════════════════════════"
echo "  PHYSYK — Robot Control via Prompts & Commands"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "✅ SERVICES STATUS:"
echo ""

# Check Physyk Server
if curl -sf http://localhost:7860/health > /dev/null 2>&1; then
    echo "  ✓ Physyk FastAPI Server: http://localhost:7860"
    echo "    API Docs: http://localhost:7860/docs"
    echo "    Status: $(curl -s http://localhost:7860/health | head -c 50)"
    echo ""
else
    echo "  ✗ Physyk server not responding"
    echo ""
fi

# Check Isaac Sim
if ps aux | grep -q "isaac.*runheadless.webrtc.sh" | grep -v grep > /dev/null; then
    echo "  ✓ Isaac Sim WebRTC Streaming: http://localhost:8080"
    echo "    Stream: http://localhost:8080/streaming/webrtc-demo/"
    echo ""
else
    echo "  ✗ Isaac Sim not found"
    echo ""
fi

echo "════════════════════════════════════════════════════════════"
echo "🤖 HOW TO MOVE THE ROBOT:"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "METHOD 1: Web UI (Easiest)"
echo "  1. Open: http://localhost:7860"
echo "  2. Type a natural language command in the prompt box"
echo "  3. Example prompts:"
echo "     - 'pick up the cube'"
echo "     - 'move to the right 10cm'"
echo "     - 'open gripper'"
echo "     - 'place the object on the table'"
echo "  4. Click 'Execute' or press Enter"
echo "  5. Watch Isaac Sim (http://localhost:8080) for real-time movement"
echo ""
echo "METHOD 2: API Endpoint (Programmatic)"
echo "  POST http://localhost:7860/execute"
echo "  Content-Type: application/json"
echo "  Body: {\"instruction\": \"pick up the cube\"}"
echo ""
echo "  Example curl:"
echo '  curl -X POST http://localhost:7860/execute \'
echo '    -H "Content-Type: application/json" \'
echo '    -d "{\"instruction\": \"pick up the red cube and move it to the left\"}"'
echo ""
echo "METHOD 3: WebSocket (Real-time Streaming)"
echo "  Connect to: ws://localhost:7860/ws"
echo "  Send: {\"type\": \"execute\", \"instruction\": \"your command here\"}"
echo "  Receive real-time joint positions and gripper state"
echo ""
echo "════════════════════════════════════════════════════════════"
echo "📝 SUPPORTED COMMANDS:"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "  Robot Control:"
echo "    - 'open gripper' / 'close gripper'"
echo "    - 'move to X Y Z' (cartesian coordinates)"
echo "    - 'pick up the [object]'"
echo "    - 'place [object] on [location]'"
echo "    - 'grasp [object]'"
echo "    - 'release [object]'"
echo ""
echo "  Movement:"
echo "    - 'move left / right / up / down'"
echo "    - 'reach toward the table'"
echo "    - 'retract arm'"
echo ""
echo "  Complex Tasks:"
echo "    - 'pick up the cube and place it in the bin'"
echo "    - 'stack the blocks'"
echo "    - 'organize the scene'"
echo ""
echo "════════════════════════════════════════════════════════════"
echo "🔗 ACCESS URLS:"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "  Local Access:"
echo "    🌐 Physyk UI:     http://localhost:7860"
echo "    🤖 Isaac Sim:     http://localhost:8080/streaming/webrtc-demo/"
echo "    📚 API Docs:      http://localhost:7860/docs"
echo "    ❤  Health Check:  http://localhost:7860/health"
echo ""
echo "🎮 START MOVING THE ROBOT NOW!"
echo ""
echo "  1. Open http://localhost:7860 in your browser"
echo "  2. Type: 'move arm to the right'"
echo "  3. Click Execute"
echo "  4. Watch the robot move in Isaac Sim!"
echo ""
echo "════════════════════════════════════════════════════════════"
