#!/bin/bash
echo "════════════════════════════════════════════════════════════"
echo "  PHYSYK — Valid Commands Guide"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "✅ The robot recognizes specific objects and destinations."
echo ""
echo "RECOGNIZED OBJECTS:"
echo "  • cube (emerald cube)"
echo "  • gear (golden gear)"
echo "  • shaft (crimson shaft)"
echo "  • housing (blue housing)"
echo ""
echo "RECOGNIZED DESTINATIONS:"
echo "  • kit / tray (kit assembly tray)"
echo "  • inspection (inspection area)"
echo "  • drop (drop zone)"
echo "  • table (staging table)"
echo ""
echo "════════════════════════════════════════════════════════════"
echo "VALID EXAMPLE COMMANDS:"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "1. PICK AND PLACE:"
echo "   ✓ 'pick up the cube'"
echo "   ✓ 'pick up the cube and place it in the kit'"
echo "   ✓ 'move the gear to the inspection area'"
echo "   ✓ 'pick up the shaft'"
echo "   ✓ 'place the housing on the table'"
echo ""
echo "2. ASSEMBLY TASKS:"
echo "   ✓ 'assemble kit a'"
echo "   ✓ 'kit a' (shorthand for assembly)"
echo "   ✓ 'assemble all objects'"
echo ""
echo "3. SPECIFIC DESTINATIONS:"
echo "   ✓ 'pick up the cube and place it in the drop zone'"
echo "   ✓ 'move the gear to inspection'"
echo "   ✓ 'place all parts on the tray'"
echo ""
echo "════════════════════════════════════════════════════════════"
echo "❌ COMMANDS THAT WON'T WORK:"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "✗ 'open gripper' (no gripper control - auto with pick/place)"
echo "✗ 'move arm to the right' (no generic movement)"
echo "✗ 'go home' (no home command)"
echo "✗ Any command without recognized objects/destinations"
echo ""
echo "════════════════════════════════════════════════════════════"
echo "🚀 HOW TO SEND COMMANDS:"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "METHOD 1: Web UI (Recommended)"
echo "  1. Open: http://localhost:7860"
echo "  2. Enter a valid command from above"
echo "  3. Click 'Execute'"
echo ""
echo "METHOD 2: API (cURL)"
curl -s -X POST http://localhost:7860/execute \
  -H "Content-Type: application/json" \
  -d '{"instruction": "pick up the cube"}' && echo ""
echo ""
echo "METHOD 3: API (Python)"
echo "  import requests"
echo "  requests.post('http://localhost:7860/execute',"
echo "    json={'instruction': 'pick up the cube'})"
echo ""
echo "════════════════════════════════════════════════════════════"
echo "✅ SERVER STATUS:"
curl -s http://localhost:7860/health | sed 's/^/  /'
echo ""
echo "════════════════════════════════════════════════════════════"
